services:
  stable-diffusion:
    image: sd-webui
    container_name: sd-webui
    command: bash webui.sh --xformers --enable-insecure-extension-access --allow-code --listen
    runtime: nvidia
    ports:
      - "7860:7860"
    volumes:
      - ./outputs:/app/stable-diffusion-webui/outputs
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
